### ISSUE TITLE
Error installing version 0.3.2

### ISSUE THREAD

**Issue by x80486** [jthegedus/asdf-v#15]
## Describe the bug

There is a compilation error while trying to install version `0.3.2`.

This is what I have installed for the `V` plugin:

```shell
$ uname --all 
Linux uplink 5.15.81-1-lts #1 SMP Fri, 02 Dec 2022 21:05:15 +0000 x86_64 GNU/Linux

$ asdf plugin list --urls 
...
v                            https://github.com/jthegedus/asdf-v

$ asdf --version 
v0.11.0-6a4f51a
```

## Steps to reproduce

```shell
$ asdf install v 0.3.2 
* Downloading v@0.3.2
* Downloaded to /home/x80486/asdf/installs/v/0.3.2
* Building v@0.3.2 from source
vlib/rand/constants/constants.v:6:19: error: overflow in implicit type `int`, use explicit type casting instead
    4 | pub const (
    5 |     lower_mask     = u64(0x00000000FFFFFFFF)
    6 |     max_u32        = 0xFFFFFFFF
      |                      ~~~~~~~~~~
    7 |     max_u64        = u64(0xFFFFFFFFFFFFFFFF)
    8 |     max_u32_as_f32 = f32(max_u32) + 1
make: *** [GNUmakefile:109: all] Error 1
* ERROR: asdf-v Could not compile v@0.3.2
* ERROR: asdf-v An error ocurred while installing v@0.3.2
```

## Expected behavior

To be able to install `V`.

## Additional context

I'm not sure if it makes more sense to download anything that could be "temporary" to `/tmp` instead, and if successful, copy over to the desired location(s).

**Comment by x80486** [comment]
I think there is something wrong with that version. I was able to install correctly most of the recent `weekly.*` ones.

**Comment by jthegedus** [comment]
I too had some issues but opted to use `weekly.*`. We can update the min version from here https://github.com/jthegedus/asdf-v/blob/99136a763efd14869190d40346289c69ce95b2f5/lib/envs.bash#L9 to `3.3` or `4.x` once it releases.
