### ISSUE TITLE
Unable to install `weekly.2023.01`

### ISSUE THREAD

**Issue by x80486** [jthegedus/asdf-v#16]
## Describe the bug

I'm trying to install the latest version and now I'm getting this error message:

```shell
[x80486@uplink:~]$ asdf install v weekly.2023.01 
* Downloading v@weekly.2023.01
* Downloaded to /home/x80486/.asdf/installs/v/weekly.2023.01
* Building v@weekly.2023.01 from source
make: cc: No such file or directory
make: *** [GNUmakefile:113: all] Error 127
* ERROR: asdf-v Could not compile v@weekly.2023.01
* ERROR: asdf-v An error ocurred while installing v@weekly.2023.01
```

As a matter of fact, every single install currently fails for me, not sure what changed. I can't tell what's going on based on the error message, but it looks quite generic :grimacing: 

## Steps to reproduce

Install weekly release using `asdf install v weekly.2023.01`

## Expected behavior

Installation should succeed.

## Additional context

```shell
[x80486@uplink:~]$ uname -a 
Linux uplink 5.15.86-1-lts #1 SMP Sun, 01 Jan 2023 16:03:00 +0000 x86_64 GNU/Linux

[x80486@uplink:~]$ make --version 
GNU Make 4.4
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I've also tried (without luck):

```shell
[x80486@uplink:~]$ CC=gcc asdf install v weekly.2023.01 
* Downloading v@weekly.2023.01
* Downloaded to /home/x80486/.asdf/installs/v/weekly.2023.01
* Building v@weekly.2023.01 from source
make: gcc: No such file or directory
make: *** [GNUmakefile:113: all] Error 127
* ERROR: asdf-v Could not compile v@weekly.2023.01
* ERROR: asdf-v An error ocurred while installing v@weekly.2023.01
```

**Comment by x80486** [comment]
By the way, I see that there is a ` v_linux.zip` file in `V`'s [releases](https://github.com/vlang/v/releases/tag/weekly.2023.01).

Would it make sense to use that instead or would it need to compile what's inside that file still? I'm trying to figure it out if what they are releasing aligns with `Go`, which is pretty much download and unzip/untar.

**Comment by jthegedus** [comment]
@x80486 Hi, I was initially using the `v_linux.zip` file before making this plugin, then they added TCC download as part of the standard V install, so I went with that instead of the zip with pre-compiled binary.

It seems though the install process depends on more things which I haven't catered for in this plugin.

The aspect of the pre-compiled binary that I found cumbersome was that the binary depends on the rest of the ZIP contents, so the binary isn't "standalone".

I cannot fix anything in the next 5 days as I am effectively afk. I can review PRs.

I would like to change this to use the zip with pre-compiled binary if possible.

**Comment by x80486** [comment]
As a side note, I've unpacked the `V` release and it comes with a bunch of other files, so it looks like it might require to build it still...but not sure.

**Comment by jthegedus** [comment]
Yeah, that's the issue with using the pre-built binaries, it's not a standalone binary, it needs to be in the repo root directory with some of the other files there.

I got the `weekly.2023.02` version working fine with this plugin and have been using that versoin. I may take another look at this soon.

**Comment by x80486** [comment]
Hi @jthegedus. Any luck at getting this one going? I gave it another whirl to version `0.3.4`, but I've got the same error.
